"use client";import { useState } from "react";import { useBalance } from "@/hooks/useBalance";import GameLayout from "@/components/layout/GameLayout";
const suits=["♠","♥","♦","♣"];const vals=["A","2","3","4","5","6","7","8","9","10","J","Q","K"];
function deck(){return suits.flatMap(s=>vals.map(v=>({s,v,n:v==="A"?11:["J","Q","K"].includes(v)?10:parseInt(v)}))).sort(()=>Math.random()-0.5);}
function total(h:any[]){let t=h.reduce((s,c)=>s+c.n,0);let a=h.filter((c:any)=>c.v==="A").length;while(t>21&&a>0){t-=10;a--;}return t;}
export default function BlackjackPage(){const{balance,placeBet,addWinnings}=useBalance();const[bet,setBet]=useState(50);const[d,setD]=useState(deck());const[p,setP]=useState<any[]>([]);const[dl,setDl]=useState<any[]>([]);const[phase,setPhase]=useState<"bet"|"play"|"end">("bet");const[msg,setMsg]=useState("");
const deal=()=>{if(!placeBet(bet))return alert("Insufficient");const dk=deck();setD(dk);setP([dk.pop()!,dk.pop()!]);setDl([dk.pop()!,dk.pop()!]);setPhase("play");};
const hit=()=>{const np=[...p,d.pop()!];setP(np);if(total(np)>21){setPhase("end");setMsg("Bust!");}};
const stand=()=>{let dh=[...dl];let dk=[...d];while(total(dh)<17)dh.push(dk.pop()!);setDl(dh);const pv=total(p),dv=total(dh);if(dv>21||pv>dv){addWinnings(bet*2);setMsg("You win!");}else if(pv===dv){addWinnings(bet);setMsg("Push");}else{setMsg("Dealer wins");}setPhase("end");};
const Card=({c,hidden}:{c?:any;hidden?:boolean})=><div className={`w-12 h-16 rounded-lg border-2 flex flex-col items-center justify-center font-bold text-sm ${hidden?"bg-blue-800 border-blue-400 text-white":"bg-white text-black"}`}>{hidden?"?":<><span>{c?.v}</span><span className="text-lg">{c?.s}</span></>}</div>;
return(<GameLayout title="🃏 Blackjack" rtp={99.5}><div className="bg-[#12121a] rounded-xl p-4 text-center mb-4"><p className="text-xs text-gray-400 mb-2">Dealer ({phase!=="bet"?total(dl):"?"})</p><div className="flex gap-2 justify-center mb-4">{dl.map((c,i)=><Card key={i} c={c} hidden={i===1&&phase==="play"}/>)}</div><p className="text-xs text-gray-400 mb-2">You ({total(p)})</p><div className="flex gap-2 justify-center">{p.map((c,i)=><Card key={i} c={c}/>)}</div>{msg&&<p className="mt-3 font-bold text-[#f0b429]">{msg}</p>}</div><div className="bg-[#12121a] rounded-xl p-4 space-y-3">{phase==="bet"?<><div className="flex gap-2"><input type="number" value={bet} onChange={e=>setBet(Number(e.target.value))} className="flex-1 bg-[#0a0a0f] border border-gray-700 rounded-lg text-white px-4 py-2"/>{[10,50,100,500].map(v=><button key={v} onClick={()=>setBet(v)} className="px-3 py-1 bg-gray-800 text-white text-xs rounded-lg">{v}</button>)}</div><button onClick={deal} className="w-full py-3 bg-[#f0b429] text-black font-bold rounded-lg">Deal</button></>:phase==="play"?<div className="flex gap-3"><button onClick={hit} className="flex-1 py-3 bg-gray-800 text-white font-bold rounded-lg">Hit</button><button onClick={stand} className="flex-1 py-3 bg-[#f0b429] text-black font-bold rounded-lg">Stand</button></div>:<button onClick={()=>{setPhase("bet");setP([]);setDl([]);setMsg("");}} className="w-full py-3 bg-[#f0b429] text-black font-bold rounded-lg">Play Again</button>}</div></GameLayout>);}